FROM debian:latest

    # install packages
    RUN apt-get update && apt-get install -y \
      wget \
      cfv \
      git \
      openssl \
      curl \
      build-essential \
      p7zip-full \
      bc \
      perl \
      python2.7 \
      pwgen

    # Nettoyage de l'image
    RUN \
        apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

    WORKDIR /tmp
    
    # Install nvm
    RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
    RUN nvm install 8.11.2
    RUN npm config set user 0
	RUN npm config set unsafe-perm true

    # Install Nyuu
    RUN npm install -g nyuu

    # Install ParPar
    RUN npm install -g @animetosho/parpar

    # Install RAR
    Run wget "http://www.rarlab.com/rar/rarlinux-x64-5.5.0.tar.gz"
    Run tar xzvf rarlinux-x64-5.5.0.tar.gz
    Run cd rar && make && make install

    RUN cd /tmp && git clone https://github.com/Diabolino/POST.git

    RUN chmod 755 /tmp/POST/bin/usenet

    ENTRYPOINT ["/tmp/POST/bin/usenet"]
    CMD ["-h"]

    # Define mountable directories.
    VOLUME ["/tmp/EXTRA"]